[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm ci"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[functions."server"]
  external_node_modules = ["pg", "ejs"]
  included_files = ["views/**", "public/**", "src/views/**", "src/public/**", "server.js"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
